Revert "Monit: add libxcrypt as dependency to fix undefined reference to crypt function in util.c"
This reverts commit fe87d2955b4412cb16fc6ea8a72a71643600a3c0.